# 配置
#   密钥 NPM_TOKEN

name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Authenticate with Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ./.npmrc
          echo "git-checks=false" >> ./.npmrc
          npm whoami

      - name: Publish to npm
        run: npm publish
